#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/avakhov/vim-colors.git",
  "git://github.com/avakhov/vim-rails.git",
  "git://github.com/avakhov/snipmate.vim.git",
  "git://github.com/avakhov/git-vim.git",
  "git://github.com/avakhov/vim-json.git",
  "git://github.com/scrooloose/nerdtree.git",
  "https://github.com/tomtom/tcomment_vim.git",
  "https://github.com/cakebaker/scss-syntax.vim.git",
  "https://github.com/kchmck/vim-coffee-script.git",
  "https://github.com/vim-scripts/bufferlist.vim.git"
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.expand_path("../bundle", __FILE__)
FileUtils.mkdir_p bundles_dir

if ARGV.first == 'me'
  git_bundles.map! do |bundle|
    bundle.sub('git://github.com/', 'git@github.com:')
  end
end

Dir.chdir bundles_dir do
  puts "Remove obsolete"
  (Dir["*"] - git_bundles.map{|g| File.basename(g, '.git')}).each do |dir|
    puts "  rm -fr #{dir}"
    FileUtils.rm_rf dir
  end

  git_bundles.each do |url|
    dir = url.split('/').last.sub(/\.git$/, '')

    puts "  Unpacking #{url} into #{dir}"
    if File.exist? dir
      Dir.chdir dir do
        system("git pull")
      end
    else
      system("git clone #{url} #{dir}")
    end
  end

  # update helptags
  vim_helptags = Dir["*/doc"].map{|d| %(-c"helptags #{d}")}.join(" ")
  cmd = "vim -e #{vim_helptags} -cquit"
  puts cmd
  `#{cmd}`
end
