#!/bin/bash

cd `dirname $0`

git_bundles=(
  git://github.com/avakhov/vim-colors.git
  git://github.com/avakhov/vim-yaml.git
  git://github.com/cakebaker/scss-syntax.vim.git
  git://github.com/kchmck/vim-coffee-script.git
  git://github.com/kien/ctrlp.vim
  git://github.com/scrooloose/nerdtree.git
  git://github.com/tomtom/tcomment_vim.git
  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-rails.git
  git://github.com/SirVer/ultisnips
  git://github.com/vim-ruby/vim-ruby
  git://github.com/jnwhiteh/vim-golang
  git://github.com/exu/pgsql.vim
  git://github.com/troydm/easybuffer.vim
  git://github.com/mustache/vim-mustache-handlebars
  git://github.com/rust-lang/rust.vim
)

mkdir -p bundle

echo Remove obsolete ...
for folder in `ls -1 bundle`
do
  remove=y
  for bundle in ${git_bundles[*]}
  do
    bundle_parts=(${bundle//\// })
    bundle_folder=${bundle_parts[${#bundle_parts[@]} - 1]%.git}
    if [ "$bundle_folder" = "$folder" ]; then
      remove=n
    fi
  done

  if [ "$remove" = "y" ]; then
    echo Remove bundle/$folder
    rm -fr bundle/$folder
  fi
done
echo Remove obsolete ... OK

echo Update existing ...
for folder in `ls -1 bundle`
do
  echo Folder: bundle/$folder
  pushd bundle/$folder > /dev/null
  git pull
  popd > /dev/null
done
echo Update existing ... OK

echo Clone new ...
for bundle in ${git_bundles[*]}
do
  install=y
  for folder in `ls -1 bundle`
  do
    bundle_parts=(${bundle//\// })
    bundle_folder=${bundle_parts[${#bundle_parts[@]} - 1]%.git}
    if [ "$bundle_folder" = "$folder" ]; then
      install=n
    fi
  done

  if [ "$install" = "y" ]; then
    pushd bundle > /dev/null
    git clone $bundle
    popd > /dev/null
  fi
done
echo Clone new ... OK

echo Update helptags ...
vim_options=
for doc in `find bundle -name doc`
do
  vim_options="$vim_options -c\"helptags $doc\""
done
cmd="vim -e $vim_options -cquit"
bash -c "${cmd}"
echo Update helptags ... OK
