#!/bin/bash

cd `dirname $0`

git_bundles=(
	https://github.com/github/copilot.vim
  https://github.com/scrooloose/nerdtree
)
base=pack/github/start

mkdir -p $base

echo Remove obsolete ...
for folder in `ls -1 $base`
do
  remove=y
  for bundle in ${git_bundles[*]}
  do
    bundle_parts=(${bundle//\// })
    bundle_folder=${bundle_parts[${#bundle_parts[@]} - 1]}
    if [ "$bundle_folder" = "$folder" ]; then
      remove=n
    fi
  done

  if [ "$remove" = "y" ]; then
    echo Remove $base/$folder
    rm -fr $base/$folder
  fi
done
echo Remove obsolete ... OK

echo Update existing ...
for folder in `ls -1 $base`
do
  echo Folder: $base/$folder
  pushd $base/$folder > /dev/null
  git pull
  popd > /dev/null
done
echo Update existing ... OK

echo Clone new ...
for bundle in ${git_bundles[*]}
do
  install=y
  for folder in `ls -1 $base`
  do
    bundle_parts=(${bundle//\// })
    bundle_folder=${bundle_parts[${#bundle_parts[@]} - 1]}
    if [ "$bundle_folder" = "$folder" ]; then
      install=n
    fi
  done

  if [ "$install" = "y" ]; then
    pushd $base > /dev/null
    git clone $bundle
    popd > /dev/null
  fi
done
echo Clone new ... OK
